export type Entity = {
	id: number;
	name: string;
};

export default [
	{
		id: 311,
		itemType: "Bundle",
		bundleType: 1,
		name: "Robloxian 2.0",
		description:
			"The first official ROBLOX body package. You get a cool new set of arms, leg, and a torso - all for one money!!!",
		productId: 369653977,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 15,
		favoriteCount: 1650949,
		offSaleDeadline: undefined,
	},
	{
		id: 652,
		itemType: "Bundle",
		bundleType: 1,
		name: "The Gnomsky Brothers",
		description:
			"After winning the gnome stacking championships, the Gnomsky brothers ran away from the circus to pursue their dreams, and became the most feared stacking attorney team in the world.",
		productId: 975594985,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 400,
		favoriteCount: 275230,
		offSaleDeadline: undefined,
	},
	{
		id: 467,
		itemType: "Bundle",
		bundleType: 1,
		name: "Jester Equinox",
		description:
			"J’adora the Jester loves to play tricks and cause mischief! Winning entry in the 2018 Rthro Design Contest. Created by Lalonyx.",
		productId: 490809819,
		itemStatus: [],
		itemRestrictions: ["Rthro"],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 250,
		favoriteCount: 269802,
		offSaleDeadline: undefined,
	},
	{
		id: 496,
		itemType: "Bundle",
		bundleType: 1,
		name: "Blazeburner",
		description: "She's small in size but packs a punch that's about 10,000 volts.",
		productId: 543842429,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 250,
		favoriteCount: 202756,
		offSaleDeadline: undefined,
	},
	{
		id: 299,
		itemType: "Bundle",
		bundleType: 1,
		name: "Superhero",
		description: "Faster than a plane, stronger than a cargo train.",
		productId: 369653965,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 230,
		favoriteCount: 1103077,
		offSaleDeadline: undefined,
	},
	{
		id: 651,
		itemType: "Bundle",
		bundleType: 1,
		name: "Steampunk Robot",
		description:
			"Sycamore Cranson was known to have built robots from his vast curiosity and ever growing ambition. But he was more well known to add a touch of dapperness to all his creations.",
		productId: 974559358,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 250,
		favoriteCount: 107855,
		offSaleDeadline: undefined,
	},
	{
		id: 126,
		itemType: "Bundle",
		bundleType: 1,
		name: "John",
		description:
			"John is one of several exclusive Roblox Avatars available for free! You can change your look at any time by selecting or buying a different avatar.\r\n",
		productId: 369653772,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 0,
		priceStatus: "Free",
		favoriteCount: 4095039,
		offSaleDeadline: undefined,
	},
	{
		id: 870,
		itemType: "Bundle",
		bundleType: 1,
		name: "Iron Bulb",
		description: "Makes for enlightening company. Created by @EternityReality.",
		productId: 1248721370,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 250,
		favoriteCount: 151715,
		offSaleDeadline: undefined,
	},
	{
		id: 671,
		itemType: "Bundle",
		bundleType: 1,
		name: "Gang O' Fries",
		description:
			"These fries look too delicious for their own good, so keep your pets away from them and they'll become your friends!\r\nThis winner of the 3rd Avatar Contest was submitted by Mxhmoud.",
		productId: 1038449815,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 250,
		favoriteCount: 381418,
		offSaleDeadline: undefined,
	},
	{
		id: 495,
		itemType: "Bundle",
		bundleType: 1,
		name: "Ud'zal",
		description:
			"The “All-Father” of the Korblox, Ud’zal was once the true master of the undead until the 12 Deathspeakers plotted his assassination. Now resurrected as an abominable creature of war, Ud’zal is forever under the control of the Deathspeakers.",
		productId: 543827446,
		itemStatus: [],
		itemRestrictions: ["Rthro"],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 250,
		favoriteCount: 1186010,
		offSaleDeadline: undefined,
	},
	{
		id: 130,
		itemType: "Bundle",
		bundleType: 1,
		name: "Lin",
		description:
			"Lin is one of several Roblox Avatars available for free! You can change your look at any time by selecting or buying a different avatar.\r\n",
		productId: 369653776,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 0,
		priceStatus: "Free",
		favoriteCount: 879333,
		offSaleDeadline: undefined,
	},
	{
		id: 954,
		itemType: "Bundle",
		bundleType: 1,
		name: "Alana of the Stars",
		description: "She's ready to blast off to the next cosmic adventure! Concept by @Sunnytamos.",
		productId: 1316389646,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 250,
		favoriteCount: 135833,
		offSaleDeadline: undefined,
	},
	{
		id: 874,
		itemType: "Bundle",
		bundleType: 1,
		name: "Bubba Doll",
		description: "Dreaming of carrot cake. Created by @Spiraxy.",
		productId: 1251819431,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 250,
		favoriteCount: 384376,
		offSaleDeadline: undefined,
	},
	{
		id: 741,
		itemType: "Bundle",
		bundleType: 1,
		name: "Linlin",
		description: "Linlin is so good at tidying up that in a split second, she cleaned up the living room!",
		productId: 1156647798,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 0,
		priceStatus: "Free",
		favoriteCount: 1284227,
		offSaleDeadline: undefined,
	},
	{
		id: 337,
		itemType: "Bundle",
		bundleType: 1,
		name: "City Life Woman",
		description: "Just a small town girl living in a blocky world / She took the midnight train going anywhere...",
		productId: 410859907,
		itemStatus: [],
		itemRestrictions: ["Rthro"],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 0,
		priceStatus: "Free",
		favoriteCount: 873606,
		offSaleDeadline: undefined,
	},
	{
		id: 429,
		itemType: "Bundle",
		bundleType: 1,
		name: "Magma Fiend",
		description: "He's got hot blood, with a temperature of nine hundred and three.",
		productId: 428346181,
		itemStatus: [],
		itemRestrictions: ["Rthro"],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 300,
		favoriteCount: 460778,
		offSaleDeadline: undefined,
	},
	{
		id: 591,
		itemType: "Bundle",
		bundleType: 1,
		name: "Mr. Toilet",
		description: "I was going to tell you a poop joke, but it stinks...",
		productId: 921803108,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 350,
		favoriteCount: 672718,
		offSaleDeadline: undefined,
	},
	{
		id: 238,
		itemType: "Bundle",
		bundleType: 1,
		name: "Man   ",
		description: "The next generation of ROBLOX.",
		productId: 369653896,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 0,
		priceStatus: "Free",
		favoriteCount: 3197892,
		offSaleDeadline: undefined,
	},
	{
		id: 589,
		itemType: "Bundle",
		bundleType: 1,
		name: "Junkbot",
		description:
			"You never wondered what happened to those toy robots you threw away years ago until they came back to life.",
		productId: 909935555,
		itemStatus: [],
		itemRestrictions: ["Rthro"],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 0,
		priceStatus: "Free",
		favoriteCount: 1833025,
		offSaleDeadline: undefined,
	},
	{
		id: 239,
		itemType: "Bundle",
		bundleType: 1,
		name: "Woman",
		description: "The next generation of ROBLOX.",
		productId: 369653897,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 0,
		priceStatus: "Free",
		favoriteCount: 6281781,
		offSaleDeadline: undefined,
	},
	{
		id: 353,
		itemType: "Bundle",
		bundleType: 1,
		name: "Skelly",
		description: "Sometimes it just feels great to rattle and shake loose your bones.",
		productId: 411582436,
		itemStatus: [],
		itemRestrictions: ["Rthro"],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 250,
		favoriteCount: 181042,
		offSaleDeadline: undefined,
	},
	{
		id: 501,
		itemType: "Bundle",
		bundleType: 1,
		name: "Oinan Thickhoof",
		description: "You better get out of the whey when the Thickhoof Clan moves through!",
		productId: 550268848,
		itemStatus: [],
		itemRestrictions: ["Rthro"],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 250,
		favoriteCount: 122621,
		offSaleDeadline: undefined,
	},
	{
		id: 592,
		itemType: "Bundle",
		bundleType: 1,
		name: "Davy Bazooka",
		description:
			"Designed by Whimy, this titan of engineering and master of imagination is on a mission to share the joy of play with his trusty Robux Launcher.",
		productId: 921922396,
		itemStatus: [],
		itemRestrictions: ["Rthro"],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 250,
		favoriteCount: 206725,
		offSaleDeadline: undefined,
	},
	{
		id: 125,
		itemType: "Bundle",
		bundleType: 1,
		name: "Oakley",
		description:
			"Oakley is one of several Roblox Avatars available for free! You can change your look at any time by selecting or buying a different avatar.\r\n",
		productId: 369653771,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 0,
		priceStatus: "Free",
		favoriteCount: 1543224,
		offSaleDeadline: undefined,
	},
	{
		id: 875,
		itemType: "Bundle",
		bundleType: 1,
		name: "Sporeling",
		description: "He's a shy, yet fungi. Created by @Spiraxy.",
		productId: 1252946190,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 250,
		favoriteCount: 199437,
		offSaleDeadline: undefined,
	},
	{
		id: 607,
		itemType: "Bundle",
		bundleType: 1,
		name: "Lindsey",
		description:
			"Roblox Line Up (roll call!)\r\n\r\nDennis (Right here!)\r\nLindsey (Hi!)\r\nKenneth (Present!)\r\nCindy (Here!)",
		productId: 950570860,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 0,
		priceStatus: "Free",
		favoriteCount: 555806,
		offSaleDeadline: undefined,
	},
	{
		id: 282,
		itemType: "Bundle",
		bundleType: 1,
		name: "ROBLOX Girl   ",
		description: "I'm a ROBLOX girl in a ROBLOX world!",
		productId: 369653944,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 0,
		priceStatus: "Free",
		favoriteCount: 302153,
		offSaleDeadline: undefined,
	},
	{
		id: 605,
		itemType: "Bundle",
		bundleType: 1,
		name: "Dennis",
		description:
			"Roblox Line Up (roll call!)\r\n\r\nDennis (Right here!)\r\nLindsey (Hi!)\r\nKenneth (Present!)\r\nCindy (Here!)",
		productId: 950563220,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 0,
		priceStatus: "Free",
		favoriteCount: 479582,
		offSaleDeadline: undefined,
	},
	{
		id: 192,
		itemType: "Bundle",
		bundleType: 1,
		name: "Korblox Deathspeaker",
		description:
			"His tribe is widely considered the best and strongest of the twelve Korblox tribes.  No one dares challenge his authority. ",
		productId: 369653841,
		itemStatus: [],
		itemRestrictions: [],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 17000,
		favoriteCount: 1595415,
		offSaleDeadline: undefined,
	},
	{
		id: 338,
		itemType: "Bundle",
		bundleType: 1,
		name: "Knights of Redcliff: Paladin",
		description:
			"The Korblox won't go down without a fight, but neither shall the Knights of Redcliff. No retreat, no surrender!",
		productId: 410112608,
		itemStatus: [],
		itemRestrictions: ["Rthro"],
		creatorHasVerifiedBadge: true,
		creatorType: "User",
		creatorTargetId: 1,
		creatorName: "Roblox",
		price: 0,
		priceStatus: "Free",
		favoriteCount: 1614562,
		offSaleDeadline: undefined,
	},
];
